name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install

      - name: Executar build
        run: yarn build
